Repository AY2223S2-CS2103-F11-1/tp, pull requests merged in 2023-04, with the labels that each got.

#256 Change user guide gui similar to below images
  docs/UserGuide.md
Labels: priority.High

#261 Removed Recur help-commands & Updated UG
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/HelpConsultationCommand.java
  src/main/java/seedu/address/logic/commands/HelpLabCommand.java
  src/main/java/seedu/address/logic/commands/HelpTutorialCommand.java
Labels: priority.High

#263 Filter fix
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/SortStudentCommand.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/SortStudentCommandParser.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/commands/SortStudentCommandTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SortStudentCommandParserTest.java
Labels: type.Bug, severity.Medium

#267 Fix minor bug
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/model/event/Consultation.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/Lab.java
  src/main/java/seedu/address/model/event/Tutorial.java
  src/main/java/seedu/address/model/event/UniqueConsultationList.java
  src/main/java/seedu/address/model/event/UniqueLabList.java
  src/main/java/seedu/address/model/event/UniqueTutorialList.java
  src/main/java/seedu/address/model/event/exceptions/NoteLengthException.java
  src/test/java/seedu/address/model/event/LabTest.java
Labels: priority.High

#274 Update ppp
  docs/team/shittake.md
Labels: priority.Low

#275 Add user guide visuals
  docs/UserGuide.md
  docs/images/AddNoteSuccess.png
  docs/images/AddStudentSuccess.png
  docs/images/AddTutorialSuccess.png
  docs/images/HelpSuccess.png
  docs/images/SortSuccess.png
  docs/images/Ui.png
  docs/images/helpUrl.png
  src/main/java/seedu/address/logic/commands/AddNoteToEventCommand.java
  src/main/java/seedu/address/logic/commands/HelpConsultationCommand.java
  src/main/java/seedu/address/logic/commands/HelpLabCommand.java
  src/main/java/seedu/address/logic/commands/HelpTutorialCommand.java
Labels: priority.High

#278 Update PPP
  docs/team/nerdyboy98.md
Labels: priority.Low

#293 Listed more contributions and added PR numbers to the PPP
  docs/DeveloperGuide.md
  docs/team/nerdyboy98.md
  src/main/java/seedu/address/logic/commands/HelpConsultationCommand.java
  src/main/java/seedu/address/logic/commands/HelpEventCommand.java
  src/main/java/seedu/address/logic/commands/HelpLabCommand.java
  src/main/java/seedu/address/logic/commands/HelpTutorialCommand.java
  src/main/java/seedu/address/logic/parser/HelpCommandParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.Low

#300 Fix bug that does not allow scroll in tableview
  docs/DeveloperGuide.md
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
Labels: priority.High

#301 Fix minor bug
  docs/UserGuide.md
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/event/UniqueConsultationList.java
  src/main/java/seedu/address/model/event/UniqueLabList.java
  src/main/java/seedu/address/model/event/UniqueTutorialList.java
  src/main/java/seedu/address/model/event/exceptions/NoteLengthException.java
  src/main/java/seedu/address/model/person/Performance.java
  src/main/java/seedu/address/model/person/Photo.java
  src/main/java/seedu/address/model/person/Remark.java
Labels: priority.High

#310 Add class diagram for comparators and sort command
  docs/DeveloperGuide.md
  docs/diagrams/SortCommandClassDiagram.puml
  docs/images/SortCommandClassDiagram.png
Labels: priority.Medium

#311 Add hyperlink to PPP & remove File add/edit help message
  docs/DeveloperGuide.md
  docs/team/nerdyboy98.md
  src/main/java/seedu/address/logic/commands/HelpConsultationCommand.java
  src/main/java/seedu/address/logic/commands/HelpEventCommand.java
  src/main/java/seedu/address/logic/commands/HelpLabCommand.java
  src/main/java/seedu/address/logic/commands/HelpTutorialCommand.java
Labels: priority.Medium

#312 Fix wrong PR number in PPP
  docs/team/nerdyboy98.md
Labels: priority.Low

#340 Fix minor syntax bugs for help commands
  src/main/java/seedu/address/logic/commands/HelpConsultationCommand.java
  src/main/java/seedu/address/logic/commands/HelpLabCommand.java
  src/main/java/seedu/address/logic/commands/HelpOrganisationCommand.java
  src/main/java/seedu/address/logic/commands/HelpStudentCommand.java
  src/main/java/seedu/address/logic/commands/HelpTutorialCommand.java
Labels: priority.Medium
