Repository AY2223S2-CS2103-F11-1/tp, pull requests merged in 2023-03, with the labels that each got.

#51 Remove traces of AB3 in UG
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Chore, priority.High

#55 Merge Help command and UG to master
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
Labels: priority.High

#49 Event sessions
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/event/Consultation.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/Lab.java
  src/main/java/seedu/address/model/event/Note.java
  src/main/java/seedu/address/model/event/Tutorial.java
  src/main/java/seedu/address/model/event/UniqueTutorialList.java
  src/main/java/seedu/address/model/event/exceptions/DuplicateTutorialException.java
  src/main/java/seedu/address/model/event/exceptions/TutorialNotFoundException.java
  src/main/java/seedu/address/storage/JsonAdaptedTutorial.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/EventCard.java
  src/main/java/seedu/address/ui/EventListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/EventListCard.fxml
  src/main/resources/view/EventListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: type.Story, priority.High

#61 Change css to light colors
  docs/DeveloperGuide.md
  src/main/java/seedu/address/ui/GreetingBar.java
  src/main/resources/view/EventListCard.fxml
  src/main/resources/view/EventListPanel.fxml
  src/main/resources/view/GreetingBar.fxml
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: priority.High

#67 Change css
  docs/DeveloperGuide.md
  src/main/java/seedu/address/ui/GreetingBar.java
  src/main/resources/view/EventListCard.fxml
  src/main/resources/view/EventListPanel.fxml
  src/main/resources/view/GreetingBar.fxml
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: priority.High

#66 [Tutorial adding command] Add null initializers for performance and remark classes
  src/main/java/seedu/address/Help.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/Performance.java
  src/main/java/seedu/address/model/person/Remark.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.High

#59 Add tableview instead of listview for students
  docs/DeveloperGuide.md
  src/main/java/seedu/address/Help.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/HelpConsultationCommand.java
  src/main/java/seedu/address/logic/commands/HelpLabCommand.java
  src/main/java/seedu/address/logic/commands/HelpTutorialCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/HelpCommandParser.java
  src/main/java/seedu/address/model/person/Performance.java
  src/main/java/seedu/address/model/person/Remark.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/GreetingBar.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/EventListCard.fxml
  src/main/resources/view/EventListPanel.fxml
  src/main/resources/view/GreetingBar.fxml
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListPanel.fxml
Labels: priority.High

#71 Add listener
  src/main/java/seedu/address/ui/GreetingBar.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/LightTheme.css
Labels: priority.High

#72 Add listener
  src/main/java/seedu/address/ui/GreetingBar.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/LightTheme.css
Labels: priority.High

#75 Add insert text to label
  src/main/java/seedu/address/ui/GreetingBar.java
Labels: priority.High

#69 Allow inputting performance indicator to students
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/PerformanceCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/PerformanceCommandParser.java
  src/main/java/seedu/address/model/person/Performance.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
Labels: priority.High

#62 Fix auto update bug
  docs/DeveloperGuide.md
Labels: priority.High

#84 Add functionality to sort students by performance level in either ascending or descending order
  src/main/java/seedu/address/model/person/Performance.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/PersonListPanel.java
Labels: priority.High

#91 Modify method name
  src/main/java/seedu/address/model/person/Performance.java
  src/main/java/seedu/address/model/person/Person.java
Labels: priority.Low

#90 Update Tutorial, Lab & Consultation help commands
  src/main/java/seedu/address/logic/commands/HelpConsultationCommand.java
  src/main/java/seedu/address/logic/commands/HelpLabCommand.java
  src/main/java/seedu/address/logic/commands/HelpTutorialCommand.java
Labels: priority.Medium

#92 Add functionality to display different colors depending on student's performance level in place of filter function for v1.2
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/PersonListPanel.java
Labels: priority.Medium

#93 Fix bugs
  src/main/java/seedu/address/ui/PersonListPanel.java
Labels: type.Bug

#104 Fix pipeline
  src/main/java/seedu/address/logic/commands/AddStudentToEventCommand.java
  src/main/java/seedu/address/logic/parser/AddStudentToEventParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High

#102 Activity events
  docs/AddEventActivityDiagram.puml
  src/main/java/seedu/address/logic/commands/AddRecurCommand.java
  src/main/java/seedu/address/logic/parser/AddLabParser.java
  src/main/java/seedu/address/logic/parser/AddRecurParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/event/Consultation.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/Lab.java
  src/main/java/seedu/address/model/event/Tutorial.java
Labels: type.Chore, priority.High

#105 Add activity help diagram
  docs/diagrams/AddEventActivityDiagram.puml
  docs/diagrams/HelpActivityDiagram.png
Labels: type.Chore, priority.High

#106 Add activity attendance
  docs/diagrams/TrAcker activity diagrams/AddEventActivityDiagram.puml
  docs/diagrams/TrAcker activity diagrams/AttendanceActivityDiagram.puml
  docs/diagrams/TrAcker activity diagrams/HelpActivityDiagram.png
  docs/diagrams/TrAcker activity diagrams/HelpActivityDiagram.txt
  docs/diagrams/TrAcker activity diagrams/MarkAttendanceActivityDiagram.png
Labels: priority.High

#107 Add student activity diagrams
  docs/diagrams/TrAcker activity diagrams/AddPerformanceActivityDiagram.png
  docs/diagrams/TrAcker activity diagrams/AddStudentToEventActivityDiagram.png
  docs/diagrams/TrAcker activity diagrams/AttendanceActivityDiagram.puml
Labels: priority.High

#108 Add student activity diagrams
  docs/diagrams/TrAcker activity diagrams/DeleteStudentFromEventActivityDiagram.png
  docs/diagrams/TrAcker activity diagrams/EditStudentInEventActivityDiagram.png
Labels: type.Chore, priority.High

#109 Add event activity diagrams
  docs/diagrams/TrAcker activity diagrams/ViewAttendanceInEventActivityDiagram.png
  docs/diagrams/TrAcker activity diagrams/ViewPerformanceInEventActivityDiagram.png
Labels: type.Chore, priority.High

#110 Add activity diagrams
  docs/diagrams/TrAcker activity diagrams/FilterStudentsActivityDiagram.png
  docs/diagrams/TrAcker activity diagrams/SortStudentsActivityDiagram.png
Labels: type.Chore, priority.High

#111 Add activity diagram
  docs/diagrams/TrAcker activity diagrams/AlertStudentActivityDiagram.png
Labels: type.Chore, priority.High

#112 Add note activity
  docs/diagrams/TrAcker activity diagrams/NoteActivityDiagram.png
Labels: type.Chore, priority.High

#116 Remove photo url
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddTutorialParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/event/Consultation.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/Lab.java
  src/main/java/seedu/address/model/event/Tutorial.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Photo.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/EventCard.java
  src/main/java/seedu/address/ui/EventListPanel.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/images/Consultation.png
  src/main/resources/images/Lab.png
  src/main/resources/images/Tutorial.png
  src/main/resources/images/attachment.png
  src/main/resources/images/noAttachment.png
  src/main/resources/images/studentProfiles/student_1.png
  src/main/resources/images/studentProfiles/student_10.png
  src/main/resources/images/studentProfiles/student_11.png
  src/main/resources/images/studentProfiles/student_12.png
  src/main/resources/images/studentProfiles/student_13.png
  src/main/resources/images/studentProfiles/student_14.png
  src/main/resources/images/studentProfiles/student_15.png
  src/main/resources/images/studentProfiles/student_2.png
  src/main/resources/images/studentProfiles/student_3.png
  src/main/resources/images/studentProfiles/student_4.png
  src/main/resources/images/studentProfiles/student_5.png
  src/main/resources/images/studentProfiles/student_6.png
  src/main/resources/images/studentProfiles/student_7.png
  src/main/resources/images/studentProfiles/student_8.png
  src/main/resources/images/studentProfiles/student_9.png
  src/main/resources/view/EventListCard.fxml
  src/main/resources/view/EventListPanel.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/PhotoCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/PhotoTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story, priority.High

#120 Change uml images
  docs/images/DeleteSequenceDiagram.png
  docs/images/DeleteSequenceEventDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
Labels: priority.High

#124 Fix bugs introduced accidentally
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
Labels: type.Bug, priority.Medium

#126 Update dg
  docs/DeveloperGuide.md
  docs/images/HelpUseCaseDiagram.png
  docs/images/NoteUseCaseDiagram.png
  docs/images/SortUseCaseDiagram.png
  docs/images/StudentUseCaseDiagram.png
  docs/images/TutorialUseCaseDiagram.png
Labels: priority.High

#127 Delete event
  docs/DeveloperGuide.md
  docs/diagrams/AddEventActivityDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/TrAcker activity diagrams/AddEventActivityDiagram.puml
  docs/images/ArchitectureSequenceDiagram 2.png
  docs/images/TrAcker-activity-diagrams/AddEventActivityDiagram.png
  docs/images/TrAcker-activity-diagrams/AddPerformanceActivityDiagram.png
  docs/images/TrAcker-activity-diagrams/AddStudentToEventActivityDiagram.png
  docs/images/TrAcker-activity-diagrams/AlertStudentActivityDiagram.png
  docs/images/TrAcker-activity-diagrams/DeleteEventActivityDiagram.png
  docs/images/TrAcker-activity-diagrams/DeleteStudentFromEventActivityDiagram.png
  docs/images/TrAcker-activity-diagrams/EditEventActivityDiagram.png
  docs/images/TrAcker-activity-diagrams/EditStudentInEventActivityDiagram.png
  docs/images/TrAcker-activity-diagrams/FilterStudentsActivityDiagram.png
  docs/images/TrAcker-activity-diagrams/HelpActivityDiagram.png
  docs/images/TrAcker-activity-diagrams/HelpActivityDiagram.txt
  docs/images/TrAcker-activity-diagrams/MarkAttendanceActivityDiagram.png
  docs/images/TrAcker-activity-diagrams/NoteActivityDiagram.png
  docs/images/TrAcker-activity-diagrams/SortStudentsActivityDiagram.png
  docs/images/TrAcker-activity-diagrams/ViewAttendanceInEventActivityDiagram.png
  docs/images/TrAcker-activity-diagrams/ViewPerformanceInEventActivityDiagram.png
  docs/images/UiClassDiagram.png
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteEventCommand.java
  src/main/java/seedu/address/logic/parser/AddConsultationParser.java
  src/main/java/seedu/address/logic/parser/AddLabParser.java
  src/main/java/seedu/address/logic/parser/AddTutorialParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/DeleteEventCommandParser.java
Labels: priority.High

#130 Delete event
  src/main/java/seedu/address/logic/commands/AddRecurCommand.java
  src/main/java/seedu/address/logic/commands/EditEventCommand.java
  src/main/java/seedu/address/logic/parser/AddRecurParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditEventCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/event/Consultation.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/Lab.java
  src/main/java/seedu/address/model/event/Tutorial.java
Labels: priority.High

#128 Updated the Error message for Student CRUD commands and updated more help commands
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpStudentCommand.java
  src/main/java/seedu/address/logic/commands/PerformanceCommand.java
  src/main/java/seedu/address/logic/commands/PhotoCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/PerformanceCommandParser.java
  src/main/java/seedu/address/logic/parser/PhotoCommandParser.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
Labels: priority.Medium

#132 Update implementation of filter function in DG
  docs/DeveloperGuide.md
Labels: priority.Medium

#141 Fix pipeline
  src/main/java/seedu/address/logic/commands/DeleteEventCommand.java
  src/main/java/seedu/address/logic/commands/EditEventCommand.java
  src/main/java/seedu/address/logic/parser/DeleteEventCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: priority.High

#144 Updated help for Event commands and fixed Student help commands
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpConsultationCommand.java
  src/main/java/seedu/address/logic/commands/HelpLabCommand.java
  src/main/java/seedu/address/logic/commands/HelpTutorialCommand.java
  src/main/java/seedu/address/logic/commands/PerformanceCommand.java
  src/main/java/seedu/address/logic/commands/PhotoCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
Labels: priority.High

#152 Fix checkstyle issues
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/SortStudentCommand.java
  src/main/java/seedu/address/logic/comparators/AddressComparator.java
  src/main/java/seedu/address/logic/comparators/EmailComparator.java
  src/main/java/seedu/address/logic/comparators/NameComparator.java
  src/main/java/seedu/address/logic/comparators/PerformanceComparator.java
  src/main/java/seedu/address/logic/comparators/RemarkComparator.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/SortStudentCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Performance.java
  src/test/java/seedu/address/logic/commands/SortStudentCommandTest.java
Labels: priority.Low

#154 Fix window add student
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
Labels: priority.High

#155 Fix null error
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
Labels: priority.High

#156 Fix help display missing bug
  src/main/java/seedu/address/logic/parser/AddLabParser.java
  src/main/java/seedu/address/logic/parser/AddNoteParser.java
  src/main/java/seedu/address/logic/parser/AddRecurParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.High

#160 Fix minor bug
  src/main/java/seedu/address/Help.java
  src/main/java/seedu/address/logic/commands/AddNoteToEventCommand.java
  src/main/java/seedu/address/logic/commands/AddStudentToEventCommand.java
  src/main/java/seedu/address/logic/commands/DeleteNoteCommand.java
  src/main/java/seedu/address/logic/commands/EditNoteCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/parser/AddConsultationParser.java
  src/main/java/seedu/address/logic/parser/AddLabParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/ui/EventCard.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/EventListCard.fxml
  src/main/resources/view/LightTheme.css
Labels: priority.High

#161 Add command navigation for Student & Event tab
  src/main/java/seedu/address/logic/commands/HelpOrganisationCommand.java
Labels: priority.Medium

#163 Add new CRUD commands in UG
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: priority.High

#159 Add support for consultations in addStudent command
  src/main/java/seedu/address/logic/parser/AddStudentToEventParser.java
  src/test/java/seedu/address/logic/commands/AddStudentToEventCommandTest.java
Labels: priority.High

#166 Prevent duplicate person
  src/main/java/seedu/address/logic/commands/AddStudentToEventCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/Consultation.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/Lab.java
  src/main/java/seedu/address/model/event/Tutorial.java
  src/test/java/seedu/address/logic/commands/AddStudentToEventCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
Labels: priority.High

#170 Major update for event help-commands
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/HelpConsultationCommand.java
  src/main/java/seedu/address/logic/commands/HelpLabCommand.java
  src/main/java/seedu/address/logic/commands/HelpTutorialCommand.java
Labels: priority.High

#171 Updated headers, fixed typo and aligned syntax
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/HelpLabCommand.java
  src/main/java/seedu/address/logic/commands/HelpOrganisationCommand.java
  src/main/java/seedu/address/logic/commands/HelpStudentCommand.java
Labels: priority.High

#172 Fix minor bug
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteEventCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/HelpConsultationCommand.java
  src/main/java/seedu/address/logic/commands/HelpLabCommand.java
  src/main/java/seedu/address/logic/commands/HelpTutorialCommand.java
  src/main/java/seedu/address/logic/parser/AddConsultationParser.java
  src/main/java/seedu/address/logic/parser/AddLabParser.java
  src/main/java/seedu/address/logic/parser/AddTutorialParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/event/Tutorial.java
  src/main/java/seedu/address/ui/EventCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/EventListCard.fxml
Labels: priority.High

#174 Fix minor bug
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddConsultationCommand.java
  src/main/java/seedu/address/logic/commands/AddLabCommand.java
  src/main/java/seedu/address/logic/commands/AddTutorialCommand.java
  src/main/java/seedu/address/logic/commands/EditEventCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/LightTheme.css
  src/main/resources/view/PersonListPanel.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#175 Fix minor bug
  README.md
  docs/UserGuide.md
  docs/images/Mock_Ui.png
  docs/images/Ui.png
  docs/images/Ui2.png
  docs/images/Ui3.png
  docs/images/Ui4.png
  docs/index.md
Labels: priority.High

#177 Modify UG
  docs/UserGuide.md
Labels: priority.Medium

#181 Add icon
  docs/UserGuide.md
Labels: priority.Low
